// <auto-generated />
using AstaLegheFC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AstaLegheFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AstaLegheFC.Models.CalciatoreListone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Diff")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffM")
                        .HasColumnType("integer");

                    b.Property<int?>("FVM")
                        .HasColumnType("integer");

                    b.Property<int?>("FVMM")
                        .HasColumnType("integer");

                    b.Property<int>("IdListone")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QtA")
                        .HasColumnType("integer");

                    b.Property<int?>("QtAM")
                        .HasColumnType("integer");

                    b.Property<int?>("QtI")
                        .HasColumnType("integer");

                    b.Property<int?>("QtIM")
                        .HasColumnType("integer");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuoloMantra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Squadra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ListoneCalciatori");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Giocatore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreditiSpesi")
                        .HasColumnType("integer");

                    b.Property<int>("IdListone")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SquadraId")
                        .HasColumnType("integer");

                    b.Property<string>("SquadraReale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SquadraId");

                    b.ToTable("Giocatori");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Lega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreditiIniziali")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Leghe");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attaccanti")
                        .HasColumnType("integer");

                    b.Property<int>("Centrocampisti")
                        .HasColumnType("integer");

                    b.Property<int>("Crediti")
                        .HasColumnType("integer");

                    b.Property<int>("Difensori")
                        .HasColumnType("integer");

                    b.Property<int>("LegaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Portieri")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LegaId");

                    b.ToTable("Squadre");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Giocatore", b =>
                {
                    b.HasOne("AstaLegheFC.Models.Squadra", "Squadra")
                        .WithMany("Giocatori")
                        .HasForeignKey("SquadraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Squadra", b =>
                {
                    b.HasOne("AstaLegheFC.Models.Lega", "Lega")
                        .WithMany("Squadres")
                        .HasForeignKey("LegaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lega");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Lega", b =>
                {
                    b.Navigation("Squadres");
                });

            modelBuilder.Entity("AstaLegheFC.Models.Squadra", b =>
                {
                    b.Navigation("Giocatori");
                });
#pragma warning restore 612, 618
        }
    }
}
